server:
  port: 8082

spring:
  application:
    name: "CrediYa"
  devtools:
    add-properties: false
  r2dbc:
    host: localhost
    port: 5432
    database: postgres
    username: postgres
    password: prueba
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
security:
  jwt:
    secret: ${JWT_SECRET:secret-manager}
    expiration: 3600
    json-exp-roles: "/roles"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
logging:
  level:
    org.springdoc: DEBUG
